### ISSUE TITLE
Can't set options.storage

### ISSUE THREAD

**Issue by guusdk** [jsxc/jsxc#934]
I'm working on an integration of JSXC (v4.1.1) with Openfire (4.6.0-beta). Part of the integration allows an administrative user to make and persist changes to the JSXC configuration options. To be able to allow for such dynamics, the options to be used are exposed through a web endpoint (such as https://xmpp.igniterealtime.org:7483/jsxc/options.json ). 

The web page that loads the web application itself firsts loads that endpoint, and uses its content to initialize JSXC. Look at the source of https://xmpp.igniterealtime.org:7483/jsxc/ to see that in action.

I've been pretty successful in applying changes to the options to be used this way. I can pretty much add all options as documented on https://jsxc.readthedocs.io/en/latest/api.html

All, but one, that is. Whenever I try to set `options.storage` the development console of the browser logs these errors whenever I reload the page:

```
jsxc.bundle.js:2 Uncaught TypeError: t.backend.setItem is not a function
    at t.testStorage (jsxc.bundle.js:2)
    at new t (jsxc.bundle.js:2)
    at Function.t.getStorage (jsxc.bundle.js:2)
    at Function.t.getOptions (jsxc.bundle.js:2)
    at Function.t.getOption (jsxc.bundle.js:2)
    at Function.e.initialize (jsxc.bundle.js:2)
    at Function.t.init (jsxc.bundle.js:2)
    at new t (jsxc.bundle.js:2)
    at Object.success ((index):70)
    at c (jquery-3.5.1.min.js:2)
```
and
```
jsxc.bundle.js:2 Uncaught TypeError: t.backend.removeItem is not a function
    at o (jsxc.bundle.js:2)
    at jsxc.bundle.js:2
```

My experience with front-end development is limited, so I'm uncertain if this actually is an issue within JSXC. It might be me, messing up somewhere. That said, all _other_ options that I add in a similar fashion do seem to work...

**Comment by sualko** [comment]
Hi @guusdk, nice work :clap:.

In your linked source I see nothing related to storage, but I assume you are doing something like this:

```
    $(function() {
        $.getJSON('options.json', function(options) {
            //options.backend = 'localStorage';

            let jsxc = new JSXC(options);
        })
    });
```

This doesn't work, because you have to pass an implementation of the storage interface like `window.localStorage` or `window.sessionStorage`. This means you have to do it like this:

```
    $(function() {
        $.getJSON('options.json', function(options) {
            //options.backend is only allowed to be "localStorage" or "sessionStorage"
            options.backend = window[options.backend];

            let jsxc = new JSXC(options);
        })
    });
```

**Comment by guusdk** [comment]
Ah, thanks, that helped me. This should have been more obvious to me as the argument definition for the property is defined as one of two objects - I took that documentation as a list of allowable string values.

![image](https://user-images.githubusercontent.com/4253898/89108718-f44b7900-d43a-11ea-9077-d6d844c7ca9c.png)

I got this to work, using your snippet as an example:

```
if ( options.storage ) {
    // Swap out the (text-based) storage indicator with the actual instance.
    options.storage = window[options.storage];
}
```
I had to use `storage` rather than `backend` though. Was that a mistake on your end, or am I doing something different to what you are suggesting? Using `backend` gives me runtime log lines saying that the unrecognized option will be ignored.

**Comment by sualko** [comment]
> I had to use storage rather than backend though. Was that a mistake on your end, or am I doing something different to what you are suggesting?

It was a mistake on my end. Sorry, but nice to hear that you get it working. :tada:

**Comment by guusdk** [comment]
Thanks for your help. Openfire now has a plugin that installs and automatically configures JSXC. 😁

**Comment by sualko** [comment]
That's great. Thanks for your effort. If you like you can also put it to the community plugin on the installation page of our website. Just create a pr in https://github.com/jsxc/jsxc.org
