### ISSUE TITLE
IOS errors and failure

### ISSUE THREAD

**Issue by ana-jd** [jsxc/jsxc#1063]
### Actual behavior
Calls don't work on iphones since version 4.1.1 
javascript bugs are detected in jsxc.bundle.js : 
+ Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'm.permission')
+ [Warn] Error on incoming call
   -> TypeError: f.on is not a function. (In 'f.on("change", (function () { n.resetPositionOfLocalVideoElement() }))', 'f.on' is undefined) 
+ Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'a.videoElement.remove')

**Comment by sualko** [comment]
Thanks for reporting those bugs. Since I do not own an iOS device I can't verify that my commit fixes all of your issues.
